### ISSUE TITLE
我需要帮忙

### ISSUE THREAD

**Issue by naip1** [ender-zhao/CFW-custom-made#7]
v2rayN的能去除推广吗？

**Comment by naip1** [comment]
@blblbblblo

**Comment by ky57** [comment]
小白折腾了一个晚上也没把广告给去掉  求加我微信 莫辜负 我还是v30 你打包好给我app.asar 比较快    vx :    openchatbot

**Comment by Z-Siqi** [comment]
> v2rayN的能去除推广吗？


首先v2rayN的编译语言与CFW并不一样，外加我也不会使用v2rayN，因此我永远也不会对v2rayN尝试更改。

**Comment by Z-Siqi** [comment]
> 小白折腾了一个晚上也没把广告给去掉 求加我微信 莫辜负 我还是v30 你打包好给我app.asar 比较快 vx : openchatbot

由于最近比较忙，不太会做多余的事。
刚才创建了Wiki (作为尝试测试用途的创建)，可以先去看看 https://github.com/Z-Siqi/CFW-custom-made/wiki
